// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../react

declare module 'use-persisted-state-any' {
    import { Dispatch, SetStateAction } from 'react';
    function createPersistedState<S>(key: string, provider?: Pick<Storage, 'getItem' | 'setItem'> | null): ((initialState: S | (() => S)) => [S, Dispatch<SetStateAction<S>>]) | (() => [S | undefined, Dispatch<SetStateAction<S | undefined>>]);
    export default createPersistedState;
};